### ISSUE TITLE
Having issues with performing calculations

### ISSUE THREAD

**Issue by camchardukian** [theranbrig/calculator#1]
Hey Theran, I want to thank you for writing the your [React Context/Hooks guide](https://medium.com/free-code-camp/building-a-calculator-with-react-hooks-and-react-context-api-debcabbc5f54) on FreeCodeCamp's Medium. I've been trying to build a calculator similar to yours but I'm having some trouble with the calculations/doMath function. 

If I use the setNumber hook by itself, I can calculate the number correctly. The problem is that after performing my calculation, I also need to clear the storedValue so that it does not display. If I try to use the setStoredValue function, however, it seems my setNumber hook no longer works!

I studied your source code and [tried your demo on netlify](https://calc-u-later.netlify.com/), and it seems you don't have this issue. Any ideas on where I may have gone wrong with my code?

Here's the file I'm having the most trouble with and would conceivably most related to this issue:
```
import React, { useState } from 'react'

export const NumberContext = React.createContext();

const NumberProvider = props => {
  const [number, setNumber] = useState('');
  const [storedNumber, setStoredNumber] = useState('');
  const [operatorType, setOperatorType] = useState('');

const handleSetDisplayValue = num => {
  console.log('display rannnn')
  if (!number.includes('.') || num !== '.') {
    setNumber(`${(number + num).replace(/^0+/, '')}`);
  }
};

const handleClearNumber = () => {
  handleSetStoredValue();
}

const handleSetStoredValue = () => {
  setStoredNumber(number);
  setNumber('');
}

const handleClearValues = () => {
  setNumber('');
  setStoredNumber('');
  setOperatorType('');
}

const handleChooseOperatorType = (opType) => {
  if (number) {
    handleSetStoredValue();
    console.log('11111')
    setOperatorType(opType)
  }
  if (storedNumber) {
    console.log('22222')
    setOperatorType(opType)
  }
}

const handleCalculations = () => {
  console.log('calc number', number, 'calcstored', storedNumber)
  if (number && storedNumber) {
  const myValue = Number(number) + Number(storedNumber)
  setNumber(myValue);
  console.log('rrrr')
  console.log('numbererrrr', number)
  }
  handleSetStoredValue('')
  // I need the above function to reset the stored value
  // but if I call that function it seems the setNumber(myValue) does not work correctly.
  console.log('calc number end', number, 'calcstored end', storedNumber)
}

return (
  <NumberContext.Provider
  value={{
    handleClearValues,
    handleSetDisplayValue,
    handleSetStoredValue,
    handleChooseOperatorType,
    handleClearNumber,
    handleCalculations,
    operatorType,
    number,
    setNumber,
    storedNumber, 
    setStoredNumber
  }}
  >
  {props.children}
  </NumberContext.Provider>
);
};

export default NumberProvider;
```
<img width="376" alt="bug_part_1" src="https://user-images.githubusercontent.com/19788651/75103681-92d3e280-5630-11ea-8d95-048a6052fcf9.png">
<img width="370" alt="bug_part_2" src="https://user-images.githubusercontent.com/19788651/75103679-923b4c00-5630-11ea-9698-7eede189bf9a.png">
<img width="368" alt="bug_part_3" src="https://user-images.githubusercontent.com/19788651/75103677-91a2b580-5630-11ea-9f04-2a8ff79dfd86.png">
<img width="371" alt="bug_part_4" src="https://user-images.githubusercontent.com/19788651/75103675-8e0f2e80-5630-11ea-9a1e-6e25125f93b5.png">

I also have a GitHub repo with the full source code [here](https://github.com/camchardukian/ReactProjects/tree/master/react-calc).

I highly appreciate any help you or other viewers of this repo may be able to offer!

**Comment by Coolone36** [comment]
Try this in Display.js

~~~
const Display = () => {
  const { number, storedNumber, operatorType } = useContext(NumberContext);
  console.log('number is', number, 'storedNumber is', storedNumber)
  return (
    <div>
      <h2> {!number && !storedNumber ? '0' : number || storedNumber}</h2>
      <p> {!storedNumber && !number ? 'Current numbers will appear here' : `${storedNumber} ${operatorType} ${number}`}</p>
    </div>
  )
}
~~~
Try this in NumberProvider.js
~~~
const handleCalculations = () => {
  console.log('calc number', number, 'calcstored', storedNumber)
  if (number && storedNumber) {
  const myValue = Number(number) + Number(storedNumber)
    setStoredNumber('');
    setNumber(myValue);
    setOperatorType('');
    
    console.log('rrrr')
    console.log('numbererrrr', number)
  }
  // handleSetStoredValue('')
  // I need the above function to reset the stored value
  // but if I call that function it seems the setNumber(myValue) does not work correctly.
  console.log('calc number end', number, 'calcstored end', storedNumber)
}
~~~

Will still have to handle the operator type. Right now it is set to do addition as the operation.

**Comment by camchardukian** [comment]
Thanks a lot Michael!
